### ISSUE TITLE
1.16.1 model == null error

### ISSUE THREAD

**Issue by AlexProgrammerDE** [PrismarineJS/prismarine-viewer#15]
```
C:\Users\alex-\Desktop\PistonBot\node_modules\prismarine-viewer\lib\models.js:24  for (const tex in model.textures) {
                          ^

TypeError: Cannot read property 'textures' of null
    at prepareModel (C:\Users\alex-\Desktop\PistonBot\node_modules\prismarine-viewer\lib\models.js:24:27)
    at resolveModel (C:\Users\alex-\Desktop\PistonBot\node_modules\prismarine-viewer\lib\models.js:61:3)
    at prepareBlocksStates (C:\Users\alex-\Desktop\PistonBot\node_modules\prismarine-viewer\lib\models.js:161:27)
    at setupRoutes (C:\Users\alex-\Desktop\PistonBot\node_modules\prismarine-viewer\lib\common.js:13:24)
    at module.exports (C:\Users\alex-\Desktop\PistonBot\node_modules\prismarine-viewer\lib\mineflayer.js:10:3)
    at Bot.<anonymous> (C:\Users\alex-\Desktop\PistonBot\index.js:37:3)
    at Object.onceWrapper (events.js:421:28)
    at Bot.emit (events.js:327:22)
    at Client.<anonymous> (C:\Users\alex-\Desktop\PistonBot\node_modules\mineflayer\lib\plugins\health.js:13:11)
    at Object.onceWrapper (events.js:422:26)

```

idk if this is 1.16.1 related, but i hope this can get soon fixed. This seems like a awesome project.

**Comment by Karang** [comment]
ah, I see, in 1.16 they changed the prefix of the namespace: `minecraft:block/air` instead of `block/air`. Should be easy to fix.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-viewer/pull/16 it's not enough apparently

**Comment by Karang** [comment]
seems to be fixed
