### ISSUE TITLE
RTMP

### ISSUE THREAD

**Issue by Timtaran** [PrismarineJS/prismarine-viewer#210]
Can I output to RTMP server?

**Comment by Karang** [comment]
yes
here is an example: https://github.com/PrismarineJS/prismarine-viewer/blob/master/examples/twitch.js

**Comment by Timtaran** [comment]
```
Using version: 1.12
ReferenceError: document is not defined
    at getEntityMesh (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\entities.js:12:24)
    at Entities.update (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\entities.js:61:20)
    at Viewer.updateEntity (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\viewer.js:54:19)
    at WorldView.<anonymous> (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\viewer.js:68:12)
    at WorldView.emit (events.js:400:28)
    at WorldView.listenToBot (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\worldView.js:54:22)
    at module.exports (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\lib\headless.js:131:13)
    at EventEmitter.<anonymous> (D:\Timur\_Minecraft_Bot\bot_test.js:12:5)
    at Object.onceWrapper (events.js:519:28)
    at EventEmitter.emit (events.js:412:35)
TypeError: Cannot read property 'add' of undefined
    at getMesh (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\entity\Entity.js:171:49)
    at new Entity (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\entity\Entity.js:213:20)
    at getEntityMesh (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\entities.js:9:17)
    at Entities.update (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\entities.js:61:20)
    at Viewer.updateEntity (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\viewer.js:54:19)
    at WorldView.<anonymous> (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\viewer.js:68:12)
    at WorldView.emit (events.js:400:28)
    at WorldView.listenToBot (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\viewer\lib\worldView.js:54:22)
    at module.exports (D:\Timur\_Minecraft_Bot\node_modules\prismarine-viewer\lib\headless.js:131:13)
    at EventEmitter.<anonymous> (D:\Timur\_Minecraft_Bot\bot_test.js:12:5)
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-y',
    '-r',
    '20',
    '-probesize',
    '42M',
    '-i',
    'pipe:0',
    '-f',
    'flv',
    '-ac',
    '2',
    '-ar',
    '44100',
    '-vcodec',
    'libx264',
    '-g',
    '40',
    '-keyint_min',
    '20',
    '-b:v',
    '1000k',
    '-minrate',
    '1000k',
    '-maxrate',
    '1000k',
    '-pix_fmt',
    'yuv420p',
    '-s',
    '1280x720',
    '-preset',
    'ultrafast',
    '-tune',
    'film',
    '-threads',
    '4',
    '-strict',
    'normal',
    '-bufsize',
    '1000k',
    'rtmp://ovsu.mycdn.me/input/***'
  ]
}
```
