### ISSUE TITLE
drawLine -> Class constructor ka cannot be invoked without 'new'

### ISSUE THREAD

**Issue by herenickname** [PrismarineJS/prismarine-viewer#239]
NodeJS:
```js
    bot.on('path_update', (r) => {
        const lastPoint = r.path[r.path.length - 1]
        const lastPointVec3 = Vec3({ x: lastPoint.x, y: lastPoint.y + 0.5, z: lastPoint.z })
        bot.viewer.drawLine('path', [bot.entity.position.offset(0, 0.5, 0), lastPointVec3], 0xff00ff)
    })
```

Browser:
```
Using version: 1.16.4
index.js:2 Uncaught TypeError: Class constructor ka cannot be invoked without 'new'
    at new s (index.js:2:63475)
    at index.js:2:720576
    at Primitives.update (index.js:2:722330)
    at Viewer.updatePrimitive (index.js:2:724954)
    at u.<anonymous> (index.js:2:725186)
    at u.i.emit (index.js:2:1104)
    at u.emitEvent (index.js:2:763707)
    at u.onevent (index.js:2:763510)
    at u.onpacket (index.js:2:763095)
    at m.i.emit (index.js:2:1104)
```

Latest version from npm.

**Comment by Karang** [comment]
`new Vec3()`

**Comment by u9g** [comment]
https://github.com/PrismarineJS/node-vec3#usage , you're not using vec3 correctly. 
It's `const vec = Vec3(x,y,z)` NOT `const vec = Vec3({x,y,z})`

**Comment by extremeheat** [comment]
Use the Vec3 class when possible. The default export function is a wrapper which can impact performance if used in hot paths
