### ISSUE TITLE
Error: Unknown entity glow_squid

### ISSUE THREAD

**Issue by joan-teriihoania** [PrismarineJS/prismarine-viewer#244]
PV version : `1.22.0`
MC version : `1.18.1`

**Details :** Using `mineflayer` to render the world of an account logged on a `1.18.1` server shows an empty screen with entities assets being displayed weirdly. *I've tested joining other servers and rendering them, works better (blocks and entities being rendered more correctly) both in `1.18.1` and earlier version (tested `1.16.4`).*
![image](https://user-images.githubusercontent.com/36391019/151713603-23d372b1-0311-4d27-ad49-8b1a1c414464.png)

I think this may come from a compatibility issue with the `1.18.1` version of Minecraft and the glow_squid (and the ink item) support wasn't implemented in the new release (https://github.com/PrismarineJS/prismarine-viewer/pull/241). On the website side, there are errors being printed in the console (including https://github.com/PrismarineJS/prismarine-viewer/issues/238) :
```
Error: Unknown entity glow_squid
    at new t.exports (index.js:2:719755)
    at index.js:2:715510
    at Entities.update (index.js:2:716102)
    at Viewer.updateEntity (index.js:2:724939)
    at u.<anonymous> (index.js:2:725170)
    at u.i.emit (index.js:2:1938)
    at u.emitEvent (index.js:2:764211)
    at u.onevent (index.js:2:764014)
    at u.onpacket (index.js:2:763584)
    at m.i.emit (index.js:2:1938)

Error: Unknown entity item
    at new t.exports (index.js:2:719755)
    at index.js:2:715510
    at Entities.update (index.js:2:716102)
    at Viewer.updateEntity (index.js:2:724939)
    at u.<anonymous> (index.js:2:725170)
    at u.i.emit (index.js:2:1938)
    at u.emitEvent (index.js:2:764211)
    at u.onevent (index.js:2:764014)
    at u.onpacket (index.js:2:763584)
    at m.i.emit (index.js:2:1938)
```

Perhaps it's something else, but I'm not sure.

**Comment by joan-teriihoania** [comment]
Entity information not specified in https://github.com/PrismarineJS/prismarine-viewer/blob/6d527e3d6d6646acfa6c79fc7fa9e2afadb98cf8/viewer/lib/entity/entities.json

**Comment by radu-gaspar** [comment]
any plans to address this issue? ...at least a temporary fix to let the rest of the scene render if entities that are missing from https://github.com/PrismarineJS/prismarine-viewer/blob/6d527e3d6d6646acfa6c79fc7fa9e2afadb98cf8/viewer/lib/entity/entities.json are around

**Comment by rom1504** [comment]
Sounds like the easiest fix here is to add the entity in entities.json.
Do you want to do it?

**Comment by radu-gaspar** [comment]
`glow_squid` sounds easy enough... I just hope `item` doesn't refer to any/all items in item form...

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/blob/f050eaaa5e6df8c9009b9af90c54773fad66f001/data/pc/1.18/entities.json#L945
