### ISSUE TITLE
Streaming to Twitch

### ISSUE THREAD

**Issue by ItzAaronUwU** [PrismarineJS/prismarine-viewer#257]
Currently having an issue streaming to twitch. The only error that seems to show up is this:

`ReferenceError: document is not defined
    at getEntityMesh (C:\Users\Aaron\Desktop\mineflayer\node_modules\prismarine-viewer\viewer\lib\entities.js:12:24)
    at Entities.update (C:\Users\Aaron\Desktop\mineflayer\node_modules\prismarine-viewer\viewer\lib\entities.js:63:20)
    at Viewer.updateEntity (C:\Users\Aaron\Desktop\mineflayer\node_modules\prismarine-viewer\viewer\lib\viewer.js:54:19)
    at WorldView.<anonymous> (C:\Users\Aaron\Desktop\mineflayer\node_modules\prismarine-viewer\viewer\lib\viewer.js:68:12)
    at WorldView.emit (node:events:390:28)
    at EventEmitter.entitySpawn (C:\Users\Aaron\Desktop\mineflayer\node_modules\prismarine-viewer\viewer\lib\worldView.js:30:27)
    at EventEmitter.emit (node:events:390:28)
    at Client.<anonymous> (C:\Users\Aaron\Desktop\mineflayer\node_modules\mineflayer\lib\plugins\entities.js:153:11)
    at Client.emit (node:events:390:28)
    at FullPacketParser.<anonymous> (C:\Users\Aaron\Desktop\mineflayer\node_modules\minecraft-protocol\src\client.js:91:12)`

**Comment by rogermiranda1000** [comment]
Looks like https://github.com/PrismarineJS/prismarine-viewer/issues/210 , and I'm having this issue too... (it worked before)
@Timtaran as the other issue was closed, do you remember how did you fix it?

**Comment by Timtaran** [comment]
> Looks like https://github.com/PrismarineJS/prismarine-viewer/issues/210 , and I'm having this issue too... (it worked before)
> @Timtaran as the other issue was closed, do you remember how did you fix it?

-

**Comment by ItzAaronUwU** [comment]
Any update on this?

**Comment by rom1504** [comment]
fixed
