### ISSUE TITLE
TypeError: Cannot read property 'getColumnAt' of undefined

### ISSUE THREAD

**Issue by crinny** [PrismarineJS/prismarine-viewer#32]
Upon running the following code, I get this error:
```
C:\Users\crinny\node_modules\prismarine-viewer\lib\mineflayer.js:100
        const column = bot.world.getColumnAt(pos)
                                 ^

TypeError: Cannot read property 'getColumnAt' of undefined
    at loadChunk (C:\Users\crinny\node_modules\prismarine-viewer\lib\mineflayer.js:100:34)
    at C:\Users\crinny\node_modules\prismarine-viewer\lib\mineflayer.js:82:7
    at spiral (C:\Users\crinny\node_modules\prismarine-viewer\lib\mineflayer.js:13:7)
    at Namespace.<anonymous> (C:\Users\crinny\node_modules\prismarine-viewer\lib\mineflayer.js:81:5)
    at Namespace.emit (events.js:210:5)
    at Namespace.emit (C:\Users\crinny\node_modules\socket.io\lib\namespace.js:213:10)
    at C:\Users\crinny\node_modules\socket.io\lib\namespace.js:181:14
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

### Code
```js
const mineflayer = require("mineflayer")
const mineflayerViewer = require("prismarine-viewer").mineflayer

const bot = mineflayer.createBot({
    host: "mc.hypixel.net",
    port: 25565,
    username: "redacted",
    password: "redacted",
    version: "1.8.9"
})

bot.once("spawn", () => {
  mineflayerViewer(bot, { port: 3007 })
})

bot.on("kicked", (reason, loggedIn) => console.log(reason, loggedIn))
bot.on("error", err => console.log(err))

```

**Comment by Karang** [comment]
Seems like your mineflayer is not up to date
