### ISSUE TITLE
Error to run the example.

### ISSUE THREAD

**Issue by mwang808** [PrismarineJS/prismarine-viewer#324]
Hello,

I got some errors to run the headless example: https://github.com/PrismarineJS/prismarine-viewer/blob/master/examples/headless.js

Here is the error message:

/home/min/node_modules/prismarine-viewer/lib/headless.js:18
  const canvas = createCanvas(width, height)
                 ^

TypeError: createCanvas is not a function
    at module.exports (/home/min/node_modules/prismarine-viewer/lib/headless.js:18:18)
    at EventEmitter.<anonymous> (/home/min/headless1.js:12:3)
    at Object.onceWrapper (events.js:519:28)
    at EventEmitter.emit (events.js:412:35)
    at Client.<anonymous> (/home/min/node_modules/mineflayer/lib/plugins/health.js:13:11)
    at Object.onceWrapper (events.js:520:26)
    at Client.emit (events.js:412:35)
    at FullPacketParser.<anonymous> (/home/min/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:400:28)
    at addChunk (/home/min/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:298:12)

I am using ubuntu 20.04. I have installed node-canvas-webgl by npm install node-canvas-webgl

Any suggestion? Thanks.

**Comment by Sah7134** [comment]
same

**Comment by Skirlax** [comment]
Same with me.
