### ISSUE TITLE
How to use the prismarine-viewer to save the bot-view videos wihout display on the server?

### ISSUE THREAD

**Issue by OrilinZ** [PrismarineJS/prismarine-viewer#402]
I put `mineflayerViewer(bot, { output: '/data/zhz_data/Voyager/videos/output.mp4', frames: 200, width: 512, height: 512 });` in the `block:  bot.once("spawn", async () => {`

I got the failure log:
```
2023-07-21 22:37:04,376 - mineflayer - INFO - Stopping subprocess.
2023-07-21 22:37:05,377 - mineflayer - INFO - Starting subprocess with commands: ['node', '/data/zhz_data/Voyager/voyager/env/mineflayer/index.js', '3001']
2023-07-21 22:37:05,790 - mineflayer - INFO - Server started on port 3001
2023-07-21 22:37:05,790 - mineflayer - INFO - Subprocess is ready.
2023-07-21 22:37:05,803 - mineflayer - INFO - {
2023-07-21 22:37:05,803 - mineflayer - INFO - port: 35071,
2023-07-21 22:37:05,803 - mineflayer - INFO - reset: 'hard',
2023-07-21 22:37:05,803 - mineflayer - INFO - inventory: {},
2023-07-21 22:37:05,803 - mineflayer - INFO - equipment: [],
2023-07-21 22:37:05,803 - mineflayer - INFO - spread: false,
2023-07-21 22:37:05,803 - mineflayer - INFO - waitTicks: 20,
2023-07-21 22:37:05,803 - mineflayer - INFO - position: null
2023-07-21 22:37:05,803 - mineflayer - INFO - }
2023-07-21 22:37:08,042 - mineflayer - INFO - /data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/prismarine-viewer/lib/headless.js:17
2023-07-21 22:37:08,042 - mineflayer - INFO - module.exports = (bot, { viewDistance = 6, output = 'output.mp4', frames = -1, width = 512, height = 512, logFFMPEG = False, jpegOptions }) => {
2023-07-21 22:37:08,042 - mineflayer - INFO - ^
2023-07-21 22:37:08,042 - mineflayer - INFO - 
2023-07-21 22:37:08,042 - mineflayer - INFO - ReferenceError: False is not defined
2023-07-21 22:37:08,042 - mineflayer - INFO - at module.exports (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/prismarine-viewer/lib/headless.js:17:119)
2023-07-21 22:37:08,042 - mineflayer - INFO - at EventEmitter.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/index.js:55:9)
2023-07-21 22:37:08,042 - mineflayer - INFO - at Object.onceWrapper (node:events:627:28)
2023-07-21 22:37:08,042 - mineflayer - INFO - at EventEmitter.emit (node:events:525:35)
2023-07-21 22:37:08,042 - mineflayer - INFO - at Client.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/mineflayer/lib/plugins/health.js:13:11)
2023-07-21 22:37:08,042 - mineflayer - INFO - at Object.onceWrapper (node:events:628:26)
2023-07-21 22:37:08,042 - mineflayer - INFO - at Client.emit (node:events:525:35)
2023-07-21 22:37:08,042 - mineflayer - INFO - at emitPacket (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/minecraft-protocol/src/client.js:83:12)
2023-07-21 22:37:08,042 - mineflayer - INFO - at FullPacketParser.<anonymous> (/data/zhz_data/Voyager/voyager/env/mineflayer/node_modules/minecraft-protocol/src/client.js:106:9)
2023-07-21 22:37:08,042 - mineflayer - INFO - at FullPacketParser.emit (node:events:513:28)
2023-07-21 22:37:08,042 - mineflayer - INFO - 
2023-07-21 22:37:08,042 - mineflayer - INFO - Node.js v18.16.1

```

**Comment by rom1504** [comment]
this is fixed (False -> false)
