### ISSUE TITLE
Import issue when trying to use this from npm

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#9]
```
Prismarine viewer web server running on *:3007
/tmp/ppp/node_modules/express-browserify/index.js:104
                                throw err;
                                ^

Error: Cannot find module '/tmp/ppp/src/index.js' from '/tmp/ppp'
    at /tmp/ppp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/tmp/ppp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/tmp/ppp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /tmp/ppp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:169:21) {
```
when running this :
```
const mineflayer = require('mineflayer')
const mineflayerViewer = require('prismarine-viewer').mineflayer

const bot = mineflayer.createBot({
  username: 'Bot'
})

bot.once('spawn', () => {
  mineflayerViewer(bot, 3007)

  const path = [bot.entity.position.clone()]
  bot.on('move', () => {
    if (path[path.length - 1].distanceTo(bot.entity.position) > 1) {
      path.push(bot.entity.position.clone())
      bot.viewer.drawLine('path', path)
    }
  })
})

```

I guess something is hardcoded somewhere

**Comment by rom1504** [comment]
fixed
